// Generated by v0 with prompt: "A contact form for a plumbing service"
// TODO: Replace this placeholder with the actual v0-generated component

export function ContactForm() {
  return (
    <div className="p-8 text-center">
      <p className="text-gray-500">Component to be generated from v0</p>
      <p className="text-sm text-gray-400 mt-2">Prompt: "A contact form for a plumbing service"</p>
    </div>
  )
}