// Generated by v0 with prompt: "A card of information about the ocean."
// TODO: Replace this placeholder with the actual v0-generated component

export function OceanInfoCard() {
  return (
    <div className="p-8 text-center">
      <p className="text-gray-500">Component to be generated from v0</p>
      <p className="text-sm text-gray-400 mt-2">Prompt: "A card of information about the ocean."</p>
    </div>
  )
}