// Generated by v0 with prompt: "a welcome card in hot pink with 'Welcome to Tiffany's Party'"
// TODO: Replace this placeholder with the actual v0-generated component

export function PartyWelcomeCard() {
  return (
    <div className="p-8 text-center">
      <p className="text-gray-500">Component to be generated from v0</p>
      <p className="text-sm text-gray-400 mt-2">Prompt: "a welcome card in hot pink with 'Welcome to Tiffany's Party'"</p>
    </div>
  )
}