// Generated by v0 with prompt: "A recipe card for a grilled cheese sandwich"
// TODO: Replace this placeholder with the actual v0-generated component

export function RecipeCard() {
  return (
    <div className="p-8 text-center">
      <p className="text-gray-500">Component to be generated from v0</p>
      <p className="text-sm text-gray-400 mt-2">Prompt: "A recipe card for a grilled cheese sandwich"</p>
    </div>
  )
}